In [28]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [29]:
print(np.__version__)

2.1.3

In [30]:
# Reading the Dataset
dataset = pd.read_csv('CKD.csv')

In [31]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [32]:
dataset.columns

Index(['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr', 'bu',
       'sc', 'sod', 'pot', 'hrmo', 'pcv', 'wc', 'rc', 'htn', 'dm', 'cad',
       'appet', 'pe', 'ane', 'classification'],
      dtype='object')

In [33]:
dataset=pd.get_dummies(dataset,drop_first=True)

dataset

In [34]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [35]:
indep=dataset[[ 'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes',]]
dep=dataset['classification_yes']

In [54]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 0.2, random_state = 0)

In [55]:
X_train

,wc,rc,sg_b,sg_c,sg_d,sg_e,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes
340,8400.000000,8.000000,False,False,True,False,True,True,False,False,True,False,False,True,False,False
64,8408.191126,4.705597,False,False,True,False,True,True,False,False,False,False,False,True,False,False
55,6700.000000,6.000000,True,False,False,False,True,True,False,False,False,False,False,True,False,False
106,7200.000000,5.500000,True,False,False,False,True,True,False,False,False,False,False,True,False,False
300,6700.000000,4.705597,False,False,True,False,True,True,True,False,True,True,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
323,8408.191126,4.705597,False,False,False,False,True,True,False,False,True,True,True,False,True,False
192,8408.191126,4.705597,True,False,False,False,True,False,False,False,False,False,False,False,True,True
117,10200.000000,4.200000,False,False,True,False,True,False,False,False,False,False,False,True,False,False
47,10200.000000,5.000000,False,False,False,False,True,True,False,False,False,False,False,True,False,False
172,8100.000000,5.900000,False,False,False,False,True,True,False,False,False,False,False,True,False,False

In [56]:
#from sklearn.preprocessing import StandardScaler
#sc = StandardScaler()
#X_train_= sc.fit_transform(X_train)
#X_test_= sc.transform(X_test)

In [57]:
from sklearn.ensemble import RandomForestClassifier

In [58]:
#https://scikit-learn.org/stable/modules/model_evaluation.html#scoring-parameter

In [59]:
from sklearn.model_selection import GridSearchCV

param_grid = {'criterion':['gini','entropy'],
              'max_features': ['auto','sqrt','log2'],
              'n_estimators':[10,100]} 



grid = GridSearchCV(RandomForestClassifier(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1') 
   
# fitting the model for grid search 
grid.fit(X_train, y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

C:\Anaconda\Lib\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning:
20 fits failed out of a total of 60.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Anaconda\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Anaconda\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Anaconda\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Anaconda\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Anaconda\Lib\site-packages\sklearn\model_selection\_search.py:1108: UserWarning: One or more of the test scores are non-finite: [       nan        nan 0.96428756 0.96974125 0.97441974 0.97473884
        nan        nan 0.97207333 0.97220798 0.97461863 0.9772682 ]
  warnings.warn(

GridSearchCV(estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             scoring='f1', verbose=3)

In [60]:
# print best parameter after tuning 
#print(grid.best_params_) 
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(X_test) 
   

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)



# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [61]:
print(grid.best_params_)

{'criterion': 'entropy', 'max_features': 'log2', 'n_estimators': 100}

In [62]:
table=pd.DataFrame.from_dict(re)

In [63]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002713,0.000294,0.000000,0.000000,gini,auto,10,"{'criterion': 'gini', 'max_features': 'auto', ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
1,0.002960,0.000456,0.000000,0.000000,gini,auto,100,"{'criterion': 'gini', 'max_features': 'auto', ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
2,0.032618,0.002963,0.008309,0.001114,gini,sqrt,10,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.948718,0.974359,0.961039,0.962963,0.974359,0.964288,0.009566,8
3,0.212994,0.002357,0.018247,0.001353,gini,sqrt,100,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.975000,0.974359,0.962025,0.962963,0.974359,0.969741,0.005929,7
4,0.025775,0.000778,0.008019,0.000650,gini,log2,10,"{'criterion': 'gini', 'max_features': 'log2', ...",0.975000,0.974359,0.961039,0.987342,0.974359,0.974420,0.008323,4
5,0.216704,0.003946,0.017103,0.000564,gini,log2,100,"{'criterion': 'gini', 'max_features': 'log2', ...",0.987654,0.974359,0.974359,0.962963,0.974359,0.974739,0.007822,2
6,0.001952,0.000380,0.000000,0.000000,entropy,auto,10,"{'criterion': 'entropy', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
7,0.002109,0.000526,0.000000,0.000000,entropy,auto,100,"{'criterion': 'entropy', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
8,0.026657,0.000403,0.008244,0.000372,entropy,sqrt,10,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.975000,0.974359,0.961039,0.975610,0.974359,0.972073,0.005537,6
9,0.232669,0.004580,0.017175,0.000665,entropy,sqrt,100,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.975000,0.974359,0.974359,0.962963,0.974359,0.972208,0.004629,5
10,0.028712,0.003575,0.008963,0.001544,entropy,log2,10,"{'criterion': 'entropy', 'max_features': 'log2...",0.962025,0.974359,0.962025,0.987342,0.987342,0.974619,0.011323,3
11,0.199024,0.017740,0.020320,0.006106,entropy,log2,100,"{'criterion': 'entropy', 'max_features': 'log2...",0.987654,0.974359,0.974359,0.975610,0.974359,0.977268,0.005216,1

In [64]:

from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'criterion': 'entropy', 'max_features': 'log2', 'n_estimators': 100}: 1.0

In [65]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[32  0]
 [ 0 48]]

In [66]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

       False       1.00      1.00      1.00        32
        True       1.00      1.00      1.00        48

    accuracy                           1.00        80
   macro avg       1.00      1.00      1.00        80
weighted avg       1.00      1.00      1.00        80

In [51]:
table_pr=pd.DataFrame()

In [52]:
table_pr.to_csv("cm.csv",index=False)